### ISSUE TITLE
get_cert with TXT not working

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#185]

**Comment by oliwel** [comment]
Requires rework on the openssl CLI modules as "openssl x509 -text" sends the output for the text section to stdout even if -out option is provided.

**Comment by maxhq** [comment]
The tools to read the result from STDOUT instead of a temp file seem to be there already, but I failed to solve this.
Affected code: `OpenXPKI::Crypto::Backend::OpenSSL::Command::convert_cert->get_command()`.
If `OUT = 'TXT'` this return value should work but doesn't:
```perl
return {
  COMMAND => 'x509 ...',
  PARAMS => [ { TYPE => 'STDOUT' } ]
};
```
Error:
```
'__COMMAND__' => 'OpenXPKI::Crypto::Backend::OpenSSL::Command::convert_cert',
'__ERRVAL__' => 'I18N_OPENXPKI_READ_FILE_DOES_NOT_EXIST; __FILENAME__ => /var/tmp/openxpki13634Ix9zLT0R'
```
Background:
`OpenXPKI::Crypto::Toolkit->command()` also accepts a HashRef from `get_command()` like `{ COMMAND => ..., PARAMS => ...`.
The syntax for the `PARAMS` part is specified in `OpenXPKI::Crypto::CLI->execute()`.
