### ISSUE TITLE
Set shebang in cgi-bin scripts in myperl suse build

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#288]
Replace Shebang in the web-scripts from core/server/cgi-bin/ with myperl path, see also #156

**Comment by mrscotty** [comment]
The path has already been corrected in the files themselves to use '/usr/bin/perl'. MakeMaker automatically re-writes the script files (i.e. those specified in EXE_FILES) to use the path to the current perl binary. In the case of the cgi-bin scripts above, they aren't EXE_FILES because they don't belong in the scripts directory.
