### ISSUE TITLE
Add verify validator for PKCS10 upload

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#437]

**Comment by tlhackque** [comment]
The next version of Crypt::PKCS10 will provide parser support for this.

The tests confirm that it is possible to verify CSRs with RSA and DSA keys.  Feel free to lift that code; it's quite simple.

ECC keys are a problem - I haven't found a Perl module that will verify an ECDSA signature from what's available in a CSR.

Experimental code described here is in my sandbox - https://github.com/tlhackque/Crypt-PKCS10.  I'd  like a solution to the ECC signatures before I commit to the main project.  Until then, I may change things...

(The ECDSA issue is documented in the ecc test, and at http://perlmonks.org/?node_id=1173167.)

Feedback on the sandbox changes (and/or help with the ECDSA issue) welcome.

**Comment by tlhackque** [comment]
ECDSA issue in Crypt::PKCS10 is closed.  I finally found a suitable Perl module.  Sample code to verify ECC-signed CSRs is in the ecc test.

The tests all hardcode the hash type for simplicity.  It should be obvious how to adapt for the general case.

**Comment by oliwel** [comment]
Great work, thank you for the heads-up.

**Comment by oliwel** [comment]
Also need a check for "well formated", saw a PKCS10 in the wild that had double line breaks but went untill issueCert where it crashed

**Comment by tlhackque** [comment]
What crashed?  If it's Crypt::PKCS10 or if Crypt::PCKS10 is returning incorrectly parsed data, please open an issue at gknocke/Crypt-PKCS10/issues and include the faulty certificate.

Line breaks shouldn't matter if the input is PEM, as whitespace is ignored in base64.

If the input is DER, Crypt::PKCS10->new may return undef, in which case Crypt::PKCS10->error should tell you what happened.  

However, parseable doesn't mean completely well-formed.  A malicious submitter could provide values that don't make sense.  E.g. an EC point not on it's curve, or invalid UTF-8 encoding or backspaces in a name or ....

Verifying the signature may catch some of these (`examples/verify_csr` now has generalized code for that).  And it will catch any problems introduced in transmission (e.g. 8-bit unclean email, tampering, etc)

But yes, you still have to do some validation of the fields.  "Fred X<BS>Jones" vs "Fred Jones" is a policy problem.

**Comment by oliwel** [comment]
This was not for your attention ;)
You are right, Crypt::PKCS10 just ignores whitespaces but openssl does not! I just saw this today at a customer install that a user uploaded a PCSK10 request with extra newlines, anything based on Crypt::PKCS10 is happy with it but openssl crashes when it tries to sign.

I wont change Crypt::PKCS10 at this point, the comment was just for me to add a regex or the like in the validator.

**Comment by tlhackque** [comment]
That's a bug in OpenSSL.  RFC 7468.  I sent an e-mail to their bug tracker, but you might want to report it as well.  https://rt.openssl.org - user and password are 'guest'.  Or e-mail to rt@openssl.org.

I reproduced it with OpenSSL 1.02h.  Even
`openssl req -text` crashes.

Attached is a test CSR that I modified for Crypt::PKCS10 - it includes spaces, tabs, multiple newlines and long lines.  I included it with with the bug report.

While you wait for a fix, you don't need to parse base64 with a regex.   Do something like this:
 `perl -Mwarnings -Mstrict -MMIME::Base64 -e'local $/; my $x = <STDIN>; $x =~ s/.*^(-----BEGIN (?:NEW )?CERTIFICATE REQUEST-----\r?\n)(.*)^(-----END (?:NEW )?CERTIFICATE REQUEST-----).*/$1 . encode_base64(decode_base64( $2 )) . $3/ems; print $x' <t/csr1.pem | openssl req -text | less
`
This will reformat any valid PEM encoded CSR so that OpenSSL will accept it.

You may want to trap warnings, as MIME::Base64 versions handle invalid input inconsistently.

If you really want to check for invalid input, it's a bit involved.  What I do is:
`
$x  =~   
/^-----BEGIN\s(?:NEW\s)?CERTIFICATE\sREQUEST-----\s+(.*?)\s*^-----END\s(?:NEW\s)?CERTIFICATE\sREQUEST-----$/ms ) {
        $x = $1;
        $x =~ s/\s+//g; # Delete whitespace, which is legal but meaningless

        # tr~A-Za-z0-9+/=~~cd; # Stricter compliance: ignore invalid characters

        unless( $x =~ m{\A[A-Za-z0-9+/]+={0,2}\z} && ( length( $x ) % 4 == 0 ) ) {
            warn( "Invalid base64 encoding\n" ); # Invalid character or length
        }
      # $x is now valid base64, and can be decoded or repackaged.
`

[csr1.pem.txt](https://github.com/openxpki/openxpki/files/510636/csr1.pem.txt)

**Comment by oliwel** [comment]
You are right - it might be more useful to correct whitespace problems instead of bugging the user but thats another story (validators are passive in OpenXPKI so they can just check data but not change it).

**Comment by tlhackque** [comment]
**Whitespace isn't an error.**  The RFCs are clear; any amount of whitespace is allowed within base64.

OpenSSL is broken, so you might want to 'work-around OpenSSL whitespace bug' :-)

The distinction is that a work-around for OpenSSL is temporary (we hope) and is not required by other tools.

**Comment by oliwel** [comment]
Some people say openssl is an error itself but if it does not work with openssl its hard to point to a RFC and say "we wont fix" ;)

**Comment by tlhackque** [comment]
OpenSSL has acked the bug and agreed that it could do better.  So maybe it will be fixed - eventually.

I agree that you need a work-around for the OpenSSL bug.  I only object to the term 'whitespace error', which is misleading.

**Comment by tlhackque** [comment]
I thought some more about signature verification in Crypt::PKCS10.

Considering the complexity of the code required for the general case
and the burden on callers, I decided that by default Crypt::PKCS10->new()
should verify the CSR's signature.  This has been implemented
and will appear in V1.7.  (If you want details, it's in my sandbox now.)

Thus, you will automatically verify CSR signatures with no code
change on your end.

Since you've created a separate issue for the OpenSSL bug, you can probably close this issue.

With respect to the OpenSSL issue, there has been some discussion
precipitated by my bug report.  As a significant project, you may want
to contribute to the discussion and emphasize its importance to you.
You can view the ticket as described above, and add to it by e-mail to rt@openssl.org with
 "`Re: [openssl.org #4698] PEM parsing incorrect; whitespace in PEM crashes parser`"
 in the subject.

**Comment by oliwel** [comment]
the existing OpenXPKI::Server::Workflow::Validator::PKCS10 does some minimal checks and whitespace is now handled in the persister so there is no need for additional checks right now.
