### ISSUE TITLE
Move architecture to latest deb release?

### ISSUE THREAD

**Issue by JonasBVS** [openxpki/openxpki#689]
Jessie release of debian is approaching 4 years and end of LTS.

it seems an automate end-of-life of openxpki, to not move to support strech release.

i mean no plans have been released to support a future move to a supported platform, and instructions specifically tells users to use a relase on the last 20% of its lifespan, yet still claiming to be enterprise-grade!?

**Comment by oliwel** [comment]
Jessie ends in June 2020 so there is still 16 month left and we currently tend to skip stretch and directly go for Buster which should be released end of the year. 

The current build is not working due to openssl 1.1 and some changed build deps - if you can contribute an updated build script we can add this to our build routines.

If you need "enterprise grade" support we offer packages for "enterprise" distros (Ubuntu, SLES, RHEL) as a paid service.

**Comment by JonasBVS** [comment]
how is the move towards Buster/Docker compatability coming along?
is Buster supported? (docs still says Jessie)

**Comment by oliwel** [comment]
The docker containers are working but still based on Jessie. 
Buster ist basically working but there are some unsolved issues with OpenSSL 1.1 but I expect we gat the solved for the next release towards the end of summer (likely with a major version bump)
