### ISSUE TITLE
Add support for Ubuntu 16.04+

### ISSUE THREAD

**Issue by areis422** [openxpki/openxpki#692]
With Ubuntu 14.04 going out of support in April 2019, OpenXPKI needs to (emphasis on NEEDS) support newer flavors of Ubuntu, either 16.04 (xenial) or 18.04 (bionic).

If this can't be resolved before or very soon after the end of support date, I may have to look at transitioning to another product.

**Comment by oliwel** [comment]
The community edition will be available for free based on Debian, an upgrade to Debian Buster is under development. Due to several reasons we will not invest more time on community packages for Ubuntu - we are working on a docker container instead.

If you want to have native packages for Ubuntu, there is a commercial offer including packages for Ubuntu 18.04 (it uses a special perl build so this is not easily adoptable to the community edition).

Of course you are free to make the packaging work for Ubuntu - if you share your efforts we are also happy to publish the packages on the project our mirror.
