### ISSUE TITLE
Feature request: ACME server

### ISSUE THREAD

**Issue by pertoft** [openxpki/openxpki#794]
It would be really nice with support for acme / certbot clients to issue certificates.

**Comment by oliwel** [comment]
The ACME protocol has a veeeery large footprint but we have a working beta here in our lab. As this is integrated into our commercial "protocol gateway" component its unlikely that it will become OpenSource in the near future - if you are interessted please contact me via PM.

**Comment by flybyray** [comment]
> ACME protocol has a veeeery large footprint
@oliwel 
Maybe it would make sense to be part of this [acme2certifier](https://github.com/grindsa/acme2certifier) ca_handler.py - list?

**Comment by oliwel** [comment]
> > ACME protocol has a veeeery large footprint
> 
> @oliwel Maybe it would make sense to be part of this [acme2certifier](https://github.com/grindsa/acme2certifier) ca_handler.py - list?

thank you for this pointer - as this project has a generic EST client and we have a generic EST server it should work out of the box, so feel free to integrate it.

**Comment by grindsa** [comment]
@flybyray: Certificate enrollment via the generic [est ca handler](https://github.com/grindsa/acme2certifier/blob/master/docs/est.md) possible; we use OpenXPKI in our release regression since a few months.  We also released a [dedicated ca handler](https://github.com/grindsa/acme2certifier/blob/master/docs/openxpki.md) integrating into OpenXPI via the RPC server API.  Feel free to test if you are interested...
